spring.datasource.url= jdbc:postgresql://postgresql-17:5432/postgresql-icp
spring.datasource.username=postgresql-icp
spring.datasource.password=MRsF%Ah_MRsFA@h
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

server.servlet.context-path=/springboot-rest-api-sample
