
spring.datasource.url= jdbc:postgresql://localhost:5433/postgresql-icp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

server.servlet.context-path=/springboot-rest-api-sample
